# 连接池配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.127.129:3306/hr_admin_system?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456

# MybatisPlus
mybatis-plus:
  configuration:
    cache-enabled: false
    # 驼峰转换
    map-underscore-to-camel-case: true
  global-config:
    banner: false
  # 扫描实体类
  type-aliases-package: com.hr.*.entity
  # 扫描自定义SQL
  mapper-locations: classpath:com/hr/*/mapper/*.xml

# dubbo配置
dubbo:
  application:
    name: document-service
  registry:
    address: zookeeper://192.168.127.129:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.hr.document.service

